language: python
python:
  - "2.7"
addons:
  postgresql: "9.4"
services:
  - redis-server
install: "pip install -r web/requirements.txt"
before_script:
  - psql -U postgres -c "create extension postgis"
script: "cd web && python manage.py test"
