version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - static:/usr/src/app/staticfiles
      - whoosh:/usr/src/app/whoosh.idx
    env_file: .env
    command: /usr/local/bin/gunicorn decisions.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/usr/src/app/staticfiles
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    volumes:
    - database:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  database: {}
  static: {}
  whoosh: {}
